from initial_load import (
    load_comments,
    get_database_size,
)  # Execute loading in comments when program is initially run. Ignoring is already an option in the SQL so data doesn't get duplicated.
import sqlite3  # Database for comments.
from fastapi import FastAPI, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI()

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

import os

if not os.path.exists("comments.db"):
    print("Comments from JSON not found, loading now...")
    load_comments()
    print("Comments loaded from JSON")
    current_database_size = get_database_size()
    print("Current database size:", current_database_size)


# TODO: Add ability to link to parents -- Future feature of replies expected
class Comment(BaseModel):
    id: Optional[str] = None  # ID generated by checking DB size
    author: str
    text: str
    date: str
    likes: int
    image: str


def tuple_to_comment(
    tuple_data: tuple,
) -> (
    Comment
):  # SQL Lite uses tuples and they need to be converted to objects for returning
    return Comment(
        id=tuple_data[0],
        author=tuple_data[1],
        text=tuple_data[2],
        date=tuple_data[3],
        likes=tuple_data[4],
        image=tuple_data[5],
    )


@app.get("/comments", response_model=List[Comment])  # get all comments -- Everyone
def get_comments():
    print("Comments being gotten")
    conn = sqlite3.connect("comments.db")
    conn.text_factory = str  # Ensure UTF-8 text handling
    c = conn.cursor()
    c.execute("SELECT * FROM comments")
    comments = c.fetchall()
    conn.close()
    return [tuple_to_comment(comment) for comment in comments]


@app.get(
    "/comments/{comment_id}", response_model=Comment
)  # get a comment by ID -- Everyone
def get_comment(comment_id: str):
    print(
        f"Getting specific comment with ID: '{comment_id}' (type: {type(comment_id)})"
    )
    conn = sqlite3.connect("comments.db")
    c = conn.cursor()

    # Debug: Check what IDs exist in the database
    c.execute("SELECT id FROM comments LIMIT 5")
    existing_ids = c.fetchall()
    print(f"Sample existing IDs in DB: {existing_ids}")

    # Try the query
    c.execute("SELECT * FROM comments WHERE id = ?", (comment_id,))
    comment = c.fetchone()
    conn.close()

    if comment is None:
        print(f"Comment with ID '{comment_id}' not found in database")
        raise HTTPException(
            status_code=404, detail=f"Comment with ID '{comment_id}' not found"
        )
    print(f"Comment found: {comment}")
    return tuple_to_comment(comment)


@app.post(
    "/comment", response_model=Comment
)  # create a new comment -- Only author of post with user ID in header can post comment
def create_comment(
    comment: Comment, user_id: Optional[str] = Header(None, alias="user_id")
):
    print("Creating comment", comment)

    current_database_size = get_database_size()

    if user_id is None:
        raise HTTPException(status_code=401, detail="user_id header is required")

    if user_id != comment.author:
        raise HTTPException(status_code=403, detail="Forbidden")

    conn = sqlite3.connect("comments.db")
    c = conn.cursor()
    c.execute(
        "INSERT INTO comments (id, author, text, date, likes, image) VALUES (?, ?, ?, ?, ?, ?)",
        (
            current_database_size + 1,
            comment.author,
            comment.text,
            comment.date,
            comment.likes,
            comment.image,
        ),
    )
    conn.commit()
    c.execute("SELECT * FROM comments WHERE id = ?", (current_database_size + 1,))
    comment_db = c.fetchone()
    conn.close()
    print("Connection closed")
    print("Comment created successfully, user ID: ", user_id, "comment: ", comment_db)
    return tuple_to_comment(
        comment_db
    )  # return the comment so the FE can display it immediately with an ID


@app.delete(
    "/comment/{comment_id}"
)  # delete a comment, requires admin or user_id to be the same as the comment's author
def delete_comment(
    comment_id: str, user_id: Optional[str] = Header(None, alias="user_id")
):
    conn = sqlite3.connect("comments.db")
    c = conn.cursor()
    c.execute("SELECT * FROM comments WHERE id = ?", (comment_id,))
    comment = c.fetchone()

    if comment is None:
        conn.close()
        raise HTTPException(status_code=404, detail="Comment not found")

    if user_id is None:
        raise HTTPException(status_code=401, detail="user_id header is required")

    if user_id != tuple_to_comment(comment).author and user_id != "Admin":
        conn.close()
        raise HTTPException(status_code=403, detail="Forbidden")

    c.execute("DELETE FROM comments WHERE id = ?", (comment_id,))
    conn.commit()
    conn.close()
    print("Comment deleted successfully, user ID: ", user_id, "comment: ", comment)
    return {
        "message": "Comment deleted successfully",
        "comment": tuple_to_comment(comment),
    }


@app.put(
    "/comment/{comment_id}"
)  # update a comment, requires admin or user_id to be the same as the comment's author
def update_comment(
    comment_id: str,
    comment: Comment,
    user_id: Optional[str] = Header(None, alias="user_id"),
):
    if user_id is None:
        raise HTTPException(status_code=401, detail="user_id header is required")

    conn = sqlite3.connect("comments.db")
    c = conn.cursor()
    c.execute("SELECT * FROM comments WHERE id = ?", (comment_id,))
    existing_comment = c.fetchone()

    if existing_comment is None:
        raise HTTPException(status_code=404, detail="Comment not found")

    if user_id != tuple_to_comment(existing_comment).author and user_id != "Admin":
        conn.close()
        raise HTTPException(status_code=403, detail="Forbidden")

    c.execute(
        "UPDATE comments SET author = ?, text = ?, date = ?, likes = ?, image = ? WHERE id = ?",
        (
            comment.author,
            comment.text,
            comment.date,
            comment.likes,
            comment.image,
            comment_id,
        ),
    )
    c.execute("SELECT * FROM comments WHERE id = ?", (comment_id,))
    comment_new = c.fetchone()
    print("old comment: ", existing_comment)
    print("new comment: ", comment_new)
    conn.commit()
    conn.close()
    return {
        "message": "Comment updated successfully",
        "comment": tuple_to_comment(comment_new),
    }
